def hanged(i):
    if i == 0:
        print("")
    
    elif i == 1:
        print("                ")
        print("                ")
        print("                ")
        print("                ")
        print("                ")
        print("                ")
        print("  _____________ ")
        print(" /            /|")
        print("/____________/ /")
        print("|____________|/ ") 
    
    elif i == 2:
        print("                ")
        print("                ")
        print("    |           ")
        print("    |           ")
        print("    |           ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
    
    elif i == 3:
        print("                ")
        print("    ________    ")
        print("    |           ")
        print("    |           ")
        print("    |           ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
    
    elif i == 4:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |           ")
        print("    |           ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
        
    elif i == 5:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |      @    ")
        print("    |           ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
        
    elif i == 6:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |      @    ")
        print("    |      |    ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
    
    elif i == 7:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |      @    ")
        print("    |     /|    ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
    
    elif i == 8:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |      @    ")
        print("    |     /|\   ")
        print("    |           ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
    
    elif i == 9:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |      @    ")
        print("    |     /|\   ")
        print("    |     /     ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 
        
    elif i == 10:
        print("                ")
        print("    ________    ")
        print("    |      |    ")
        print("    |      @    ")
        print("    |     /|\   ")
        print("    |     / \   ")
        print("  __|__________ ")
        print(" /  |         /|")
        print("/____________/ /")
        print("|____________|/ ") 